import { Elements } from "@kontent-ai/delivery-sdk";
import Head from "next/head";
import { getItemByCodename, getItemsOfType } from "../../services/kontentClient";
import { Course } from "../../models";
import { RichTextElement } from "../../components/RichTextComponent";

interface LessonsProps{
    lessons: Elements.RichTextElement,
    courseId: string
}

export default function Lessons({lessons, courseId}:LessonsProps) {
  return (
    <>
      <Head>
        <title>Lesson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div 
       data-kontent-project-id={process.env.KONTENT_ENVIRONMENT_ID}
       data-kontent-language-codename='default'
      data-kontent-item-id={courseId}
      data-kontent-element-codename='lessons'>
        <RichTextElement element={lessons} isInsideTable={false} language={"default"} courseId={courseId}/>
      </div>
    </>
  );
  }

  export async function getStaticPaths() {
    const courses = await getItemsOfType<Course>('course', 5)
    const coursesLessonsUrls = courses.map((item) => {
      return {
        params: {
          slug: item.system.codename
        },
      };
    });
  
    return {
      paths: coursesLessonsUrls,
      fallback: false,
    };
  }
  
  export async function getStaticProps({ params }) {

    const course = await getItemByCodename<Course>(params.slug,5)
    const lessons = course.elements.lessons
    const courseId = course.system.id

  
    return {
      props: {
        courseId,
        lessons,
      },
    }
}
