import Head from "next/head";
import { getItemByCodename, getItemsOfType } from "../../services/kontentClient";
import Layout from "../../components/Layout";
import type { Course } from "../../models";

interface CoursesProps {
    courses:Array<Course>
  }

export default function Course({courses}:CoursesProps) {
  return (
    <>
      <Head>
        <title>{courses[0].elements.title.value}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout courses={courses} />
    </>
  );
  }

  export async function getStaticPaths() {
    const courses = await getItemsOfType<Course>('course', 5)
    const coursesUrls = courses.map((item) => {
      return {
        params: {
          slug: item.system.codename
        },
      };
    });
  
    return {
      paths: coursesUrls,
      fallback: false,
    };
  }
  
  export async function getStaticProps({ params }) {

    const course = await getItemByCodename<Course>(params.slug,5)

    const courses = [course]

  
    return {
      props: {
        courses,
      },
    }
}
