import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type CourseCategory } from '../taxonomies/course_category.js';
import { type CourseLevel } from '../taxonomies/course_level.js';

/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Course
 * Id: ebbb772f-881e-53d6-8a13-cffc3fc93876
 * Codename: course
 */
export type Course = IContentItem<{
    /**
     * Average completion time (text)
     * Required: true
     * Id: f84a3d47-fec2-4c32-9203-662b28256c2e
     * Codename: average_completion_time
     */
    averageCompletionTime: Elements.TextElement;

    /**
     * Banner Background (asset)
     * Required: true
     * Id: 7bc2daa2-bade-4384-ada2-9ce78fb13087
     * Codename: banner_background
     */
    bannerBackground: Elements.AssetsElement;

    /**
     * Course Category (taxonomy)
     * Required: false
     * Id: 0c44f367-57cd-52c7-a993-4d4c4d9709b6
     * Codename: course_category
     */
    courseCategory: Elements.TaxonomyElement<CourseCategory>;

    /**
     * Course Level (taxonomy)
     * Required: false
     * Id: b1ffe50c-bfc3-4ab6-864b-e2e7ad6438aa
     * Codename: course_level
     */
    courseLevel: Elements.TaxonomyElement<CourseLevel>;

    /**
     * Description (rich_text)
     * Required: false
     * Id: ab0d1a5a-7218-5206-8e62-c15f39d89aed
     * Codename: description
     */
    description: Elements.RichTextElement;

    /**
     * End Date (date_time)
     * Required: false
     * Id: 7ecffba8-7fa5-5f46-bd6e-7c3690a0e64c
     * Codename: end_date
     */
    endDate: Elements.DateTimeElement;

    /**
     * Image (asset)
     * Required: false
     * Id: ba4ad103-95b1-514f-9ed3-b6edadfc7a50
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Lessons (rich_text)
     * Required: true
     * Id: ea824527-8ce8-43e9-9037-ca9f208aae3f
     * Codename: lessons
     */
    lessons: Elements.RichTextElement;

    /**
     * Start Date (date_time)
     * Required: false
     * Id: a6963fac-f176-5cab-b800-ba9fd96900db
     * Codename: start_date
     */
    startDate: Elements.DateTimeElement;

    /**
     * Summary (text)
     * Required: true
     * Id: d3bb03cf-640f-4b73-bcd9-33e8e03b5693
     * Codename: summary
     */
    summary: Elements.TextElement;

    /**
     * Title (text)
     * Required: true
     * Id: 20ddc927-5264-582b-b385-feb443910298
     * Codename: title
     */
    title: Elements.TextElement;

    /**
     * Topics (rich_text)
     * Required: false
     * Id: 39906d63-11a5-4604-a4e9-4613248f4ef1
     * Codename: topics
     */
    topics: Elements.RichTextElement;

    /**
     * Weekly Scheduled Times (text)
     * Required: false
     * Id: 474d595d-c75f-5730-b221-b680f70da7ca
     * Codename: weekly_scheduled_times
     */
    weeklyScheduledTimes: Elements.TextElement;
}>;
