import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Fact
 * Id: 5a6b10c6-c69b-483e-a602-77244f4e98a8
 * Codename: fact
 */
export type Fact = IContentItem<{
    /**
     * Body (text)
     * Required: true
     * Id: 53af13eb-4533-4a27-bfd0-d2d2208494c0
     * Codename: body
     */
    body: Elements.TextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: e88c70df-10c3-4b1a-b67f-48944ab299c5
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Title (text)
     * Required: false
     * Id: eb28776c-106f-4e9d-9f51-20ac662090bb
     * Codename: title
     */
    title: Elements.TextElement;
}>;
