/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Course Level
 * Id: 4a57a8a5-1f6d-43aa-9829-c0766b88cef1
 * Codename: course_level
 */
export type CourseLevel = 'basic' | 'intermediate' | 'strategic';
