/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 *
 * Course Category
 * Id: 45ac1ca5-523a-5eae-907e-d7cd1cda8b43
 * Codename: course_category
 */
export type CourseCategory = 'designation_course' | 'micro_course' | 'topic_course';
