/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const assetFolders = {
    /**
     * Course backgrounds
     */
    courseBackgrounds: {
        id: '8fe1fdc6-c085-4542-8906-92ab0487f2cb',
        name: 'Course backgrounds',
        externalId: undefined,
        folders: {}
    },

    /**
     * Lesson backgrounds
     */
    lessonBackgrounds: {
        id: '1606ed5c-077f-48b8-9db3-aa88b344d4a7',
        name: 'Lesson backgrounds',
        externalId: undefined,
        folders: {}
    }
} as const;
