/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const contentTypes = {
    /**
     * Course
     */
    course: {
        codename: 'course',
        id: 'ebbb772f-881e-53d6-8a13-cffc3fc93876',
        externalId: '610c14cd-5bf3-4a95-9880-a16c8bda9674',
        name: 'Course',
        elements: {
            /**
             * Average completion time (text)
             */
            average_completion_time: {
                codename: 'average_completion_time',
                id: 'f84a3d47-fec2-4c32-9203-662b28256c2e',
                externalId: undefined,
                name: 'Average completion time',
                required: true,
                type: 'text'
            },

            /**
             * Banner Background (asset)
             */
            banner_background: {
                codename: 'banner_background',
                id: '7bc2daa2-bade-4384-ada2-9ce78fb13087',
                externalId: undefined,
                name: 'Banner Background',
                required: true,
                type: 'asset'
            },

            /**
             * Course Category (taxonomy)
             */
            course_category: {
                codename: 'course_category',
                id: '0c44f367-57cd-52c7-a993-4d4c4d9709b6',
                externalId: '04ca0cce-8eee-45e8-bd25-fb1c13d0b3fb',
                name: 'Course category',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Course Level (taxonomy)
             */
            course_level: {
                codename: 'course_level',
                id: 'b1ffe50c-bfc3-4ab6-864b-e2e7ad6438aa',
                externalId: undefined,
                name: 'Course Level',
                required: false,
                type: 'taxonomy'
            },

            /**
             * Description (rich_text)
             */
            description: {
                codename: 'description',
                id: 'ab0d1a5a-7218-5206-8e62-c15f39d89aed',
                externalId: 'b0559834-59a7-4dc2-94cb-1b99a79ceb5d',
                name: 'Description',
                required: false,
                type: 'rich_text'
            },

            /**
             * End Date (date_time)
             */
            end_date: {
                codename: 'end_date',
                id: '7ecffba8-7fa5-5f46-bd6e-7c3690a0e64c',
                externalId: '74b13f22-a389-4a22-8a83-fcbe23ac0e1e',
                name: 'End Date',
                required: false,
                type: 'date_time'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: 'ba4ad103-95b1-514f-9ed3-b6edadfc7a50',
                externalId: 'b8ab15e1-bb31-4c82-b85b-5c62fe87a4ad',
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Lessons (rich_text)
             */
            lessons: {
                codename: 'lessons',
                id: 'ea824527-8ce8-43e9-9037-ca9f208aae3f',
                externalId: undefined,
                name: 'Lessons',
                required: true,
                type: 'rich_text'
            },

            /**
             * Start Date (date_time)
             */
            start_date: {
                codename: 'start_date',
                id: 'a6963fac-f176-5cab-b800-ba9fd96900db',
                externalId: '55694d24-7c7d-4280-9590-0d1b137d4f4a',
                name: 'Start Date',
                required: false,
                type: 'date_time'
            },

            /**
             * Summary (text)
             */
            summary: {
                codename: 'summary',
                id: 'd3bb03cf-640f-4b73-bcd9-33e8e03b5693',
                externalId: undefined,
                name: 'Summary',
                required: true,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '20ddc927-5264-582b-b385-feb443910298',
                externalId: '1e4272e3-7d10-492d-9df7-9e1e391ebef4',
                name: 'Title',
                required: true,
                type: 'text'
            },

            /**
             * Topics (rich_text)
             */
            topics: {
                codename: 'topics',
                id: '39906d63-11a5-4604-a4e9-4613248f4ef1',
                externalId: undefined,
                name: 'Topics',
                required: false,
                type: 'rich_text'
            },

            /**
             * Weekly Scheduled Times (text)
             */
            weekly_scheduled_times: {
                codename: 'weekly_scheduled_times',
                id: '474d595d-c75f-5730-b221-b680f70da7ca',
                externalId: '321fee5b-286a-4460-8b3b-9b571495bd84',
                name: 'Weekly Scheduled Times',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Fact
     */
    fact: {
        codename: 'fact',
        id: '5a6b10c6-c69b-483e-a602-77244f4e98a8',
        externalId: undefined,
        name: 'Fact',
        elements: {
            /**
             * Body (text)
             */
            body: {
                codename: 'body',
                id: '53af13eb-4533-4a27-bfd0-d2d2208494c0',
                externalId: undefined,
                name: 'Body',
                required: true,
                type: 'text'
            },

            /**
             * Image (asset)
             */
            image: {
                codename: 'image',
                id: 'e88c70df-10c3-4b1a-b67f-48944ab299c5',
                externalId: undefined,
                name: 'Image',
                required: false,
                type: 'asset'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'eb28776c-106f-4e9d-9f51-20ac662090bb',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Lesson
     */
    lesson: {
        codename: 'lesson',
        id: '92e57bd1-983a-466f-8f4d-d721d4279950',
        externalId: undefined,
        name: 'Lesson',
        elements: {
            /**
             * Background Image (asset)
             */
            background_image: {
                codename: 'background_image',
                id: '074dc486-da86-424e-a760-3e39affc3dd3',
                externalId: undefined,
                name: 'Background Image',
                required: false,
                type: 'asset'
            },

            /**
             * Content (rich_text)
             */
            content: {
                codename: 'content',
                id: '447aa7ed-2ce1-4915-be67-38a34b73b9fe',
                externalId: undefined,
                name: 'Content',
                required: false,
                type: 'rich_text'
            },

            /**
             * Header (text)
             */
            header: {
                codename: 'header',
                id: '6a3489b5-6703-455d-b93e-16a08810f63a',
                externalId: undefined,
                name: 'Header',
                required: true,
                type: 'text'
            },

            /**
             * Sub header (text)
             */
            sub_header: {
                codename: 'sub_header',
                id: '32cc59ad-f58d-4100-9b2c-273990f486b3',
                externalId: undefined,
                name: 'Sub header',
                required: false,
                type: 'text'
            }
        }
    }
} as const;
