/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '3ecb42cf-ab8e-42c1-8681-e5213f8c7567',
        name: 'Project manager'
    }
} as const;
