/**
 * Generated by '@kontent-ai/model-generator@7.3.0'
 */
export const taxonomies = {
    /**
     * Course Category
     */
    course_category: {
        codename: 'course_category',
        id: '45ac1ca5-523a-5eae-907e-d7cd1cda8b43',
        externalId: 'ccda27a2-779d-47a6-98bc-ec23ce2fc868',
        name: 'Course Category',
        terms: {
            designation_course: {
                codename: 'designation_course',
                id: '629994aa-8165-5719-9023-33587b910e2e',
                externalId: 'd79fcf26-b534-4756-bfbf-8923b2208caf',
                name: 'Designation Course',
                terms: {}
            },
            micro_course: {
                codename: 'micro_course',
                id: '16a98b86-13da-5f12-a4ac-7c54bc9b05cc',
                externalId: '046ee160-ca7e-4b9f-8118-4a99e8279222',
                name: 'Micro Course',
                terms: {}
            },
            topic_course: {
                codename: 'topic_course',
                id: '0b57a81a-aa2f-5e88-bcd7-5a312c0f7225',
                externalId: '8eb55267-cc57-4b44-b13d-2c229baaec41',
                name: 'Topic Course',
                terms: {}
            }
        }
    },

    /**
     * Course Level
     */
    course_level: {
        codename: 'course_level',
        id: '4a57a8a5-1f6d-43aa-9829-c0766b88cef1',
        externalId: undefined,
        name: 'Course Level',
        terms: {
            basic: {
                codename: 'basic',
                id: '7c3a8697-525d-48c3-89c4-a3bd82fc2934',
                externalId: undefined,
                name: 'Basic',
                terms: {}
            },
            intermediate: {
                codename: 'intermediate',
                id: '07c713ac-3e25-4c8b-bb8f-6d0b4d307870',
                externalId: undefined,
                name: 'Intermediate',
                terms: {}
            },
            strategic: {
                codename: 'strategic',
                id: 'e670cf08-a41e-41a7-95b5-41762f92bf14',
                externalId: undefined,
                name: 'Strategic',
                terms: {}
            }
        }
    }
} as const;
