import Head from "next/head";
import Layout from "../components/Layout";
import { Course } from "../models";
import { getItemsOfType } from "../services/kontentClient";

//TODO:
// Make Slide navigation experience "next slide" 
// Rich Text resolver is critical
// Preview is critical

interface CoursesProps{
  courses:Course[]
}

export default function Home({courses}:CoursesProps) {
  return (
    <>
      <Head>
        <title>Courses</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout courses={courses} />
    </>
  );
}

export const getStaticProps = async () => {
  const courses = await getItemsOfType<Course>('course',3, 10)
  
  return {
    props: {
      courses
    },
  };
};
